### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kaartik7**
Added documentation to all methods, variables and classes of player and its subclasses. Cleaned the code and made minor changes in methods.

### CODE REVIEW

**Review by 1izardo — CHANGES_REQUESTED** [review]
These files should be placed in the correct package(s) under `src/main/java`.

**Comment by Kaartik7** [comment]
> 

Made the necessary change

**Review by 1izardo — APPROVED** [review]

**Review by sack6oy — APPROVED** [review]
I approve of these changes!

**Review by m-parvaneh — APPROVED** [review]
Everything looks good! 💯

**Review by adityaperi24 — APPROVED** [review]
Changes Approved!

**Pull request merged**
