### PR TITLE
Clean Arch Diagram

### PR DESCRIPTION
**Pull request by Kaartik7**
The following is the clean arch diagram our documentation should have. It is currently a word doc, feel free to annotate and edit it, we will paste a screenshot of the same in our documentation once it is final.

### CODE REVIEW

**Review by 1izardo — COMMENTED** [review]
Good so far! We can probably add a little bit more once our code is more final.

**Review by m-parvaneh — APPROVED** [review]
Good representation of the code so far!

**Review by adityaperi24 — APPROVED** [review]
Approved

**Comment by 1izardo** [comment]
This was incorporated into #52

**Pull request closed without merging**
