### PR TITLE
Added Functionality to view a player individually

### PR DESCRIPTION
**Pull request by adityaperi24**

### CODE REVIEW

**Review by m-parvaneh — APPROVED** [review]
Outstanding! 😈

**Review by 1izardo — APPROVED** [review]
Fantastic work!

**Review by Kaartik7 — APPROVED** [review]
great

**Review by Kaartik7 — APPROVED** [review]
nice!

**Review by sack6oy — APPROVED** [review]
Looks great! Can't wait to use this to implement User team creation, thanks!

**Pull request merged**
