### PR TITLE
Database refactoring

### LINKED ISSUE #27: Make databases less static
Refactor database classes so that methods and variables are no longer static. Linked to #28.

### PR DESCRIPTION
**Pull request by 1izardo**
Includes changes necessary to resolve #27 and #28.

### CODE REVIEW

**Review by m-parvaneh — APPROVED** [review]
Changes look good, lots of really crucial refactoring taken care of! 🥇

**Comment by sack6oy** [comment]
Great additional changes as a result of our rethinking of our Databases and how user logins should work! 😀

**Review by sack6oy — APPROVED** [review]
I like these changes! 👍

**Review by Kaartik7 — APPROVED** [review]
Looks right

**Review by adityaperi24 — APPROVED** [review]
The changes look good to me, approved

**Review by MichaelUmeh007 — APPROVED** [review]

**Pull request merged**
