### PR TITLE
Remove unnecessary folders

### PR DESCRIPTION
**Pull request by 1izardo**
Removed the `.vscode` folder (accidentally pushed), the `lib` folder (no longer necessary), and the `player_properties.txt` file (no longer used).

### CODE REVIEW

**Review by MichaelUmeh007 — APPROVED** [review]
Nice clean up

**Review by sack6oy — APPROVED** [review]
I approve of this change. - Tobey <3

**Review by m-parvaneh — APPROVED** [review]
Reduces clutter since files were no longer needed. Great work!

**Review by Kaartik7 — APPROVED** [review]
Lovely work 💯

**Comment by adityaperi24** [comment]
Approved

**Review by adityaperi24 — APPROVED** [review]
Approved

**Pull request merged**
